/**
 * 职业相关常量
 */

export const PROFESSIONS = {
  GUARDIAN: 'Guardian',
  WARRIOR: 'Warrior',
  ENGINEER: 'Engineer',
  RANGER: 'Ranger',
  THIEF: 'Thief',
  ELEMENTALIST: 'Elementalist',
  MESMER: 'Mesmer',
  NECROMANCER: 'Necromancer',
  REVENANT: 'Revenant',
  HERALD: 'Herald',
  DRAGONHUNTER: 'Dragonhunter',
  BERSERKER: 'Berserker',
  SPELLBREAKER: 'Spellbreaker',
  SCRAPPER: 'Scrapper',
  HOLOSMITH: 'Holosmith',
  DRUID: 'Druid',
  SOULBEAST: 'Soulbeast',
  DAREDEVIL: 'Daredevil',
  DEADEYE: 'Deadeye',
  TEMPEST: 'Tempest',
  WEAVER: 'Weaver',
  CHRONOMANCER: 'Chronomancer',
  MIRAGE: 'Mirage',
  REAPER: 'Reaper',
  SCOURGE: 'Scourge',
  VINDICATOR: 'Vindicator',
  UNTAMED: 'Untamed',
  WILLBENDER: 'Willbender',
  BLADESWORN: 'Bladesworn',
  VIRTUOSO: 'Virtuoso',
  HARBINGER: 'Harbinger',
  CATALYST: 'Catalyst',
  SPECTER: 'Specter',
  MECHANIST: 'Mechanist'
}

export const PROFESSION_TRANSLATIONS = {
  'Guardian': '守护者',
  'Warrior': '战士',
  'Engineer': '工程师',
  'Ranger': '游侠',
  'Thief': '潜行者',
  'Elementalist': '元素使',
  'Mesmer': '幻术师',
  'Necromancer': '唤灵师',
  'Revenant': '魂武者',
  'Berserker': '狂战士',
  'Spellbreaker': '破法者',
  'Willbender': '誓剑士',
  'Dragonhunter': '圣言士',
  'Tempest': '燃火者',
  'Weaver': '破锋者',
  'Catalyst': '猎龙者',
  'Chronomancer': '圣辉者',
  'Herald': '预告者',
  'Renegade': '龙魂使',
  'Vindicator': '裁决者',
  'Druid': '德鲁伊',
  'Soulbeast': '魂兽师',
  'Untamed': '狂兽师',
  'Deadeye': '风羽者',
  'Scrapper': '机械师',
  'Holosmith': '全息师',
  'Mechanist': '玉偃师',
  'Daredevil': '流金师',
  'Specter': '独行侠',
  'Deadeye': '神枪手',
  'Mirage': '缚影者',
  'Virtuoso': '夜刃',
  'Reaper': '夺魂者',
  'Scourge': '灾厄师',
  'Harbinger': '先驱者',
  'Weaver': '祭祀者',
  'Chronomancer': '时空术士',
  'Mirage': '幻象术士',
  'Virtuoso': '灵刃术士',
  'Mesmer': '吟游诗人'
}

export const PROFESSION_COLORS = {
  'Guardian': 'bg-yellow-100 text-yellow-800',
  '守护者': 'bg-yellow-100 text-yellow-800',
  'Warrior': 'bg-red-100 text-red-800',
  '战士': 'bg-red-100 text-red-800',
  'Engineer': 'bg-orange-100 text-orange-800',
  '工程师': 'bg-orange-100 text-orange-800',
  'Ranger': 'bg-green-100 text-green-800',
  '游侠': 'bg-green-100 text-green-800',
  'Thief': 'bg-gray-200 text-gray-800',
  '潜行者': 'bg-gray-200 text-gray-800',
  'Elementalist': 'bg-cyan-100 text-cyan-800',
  '元素使': 'bg-cyan-100 text-cyan-800',
  'Mesmer': 'bg-purple-100 text-purple-800',
  '幻术师': 'bg-purple-100 text-purple-800',
  'Necromancer': 'bg-gray-300 text-gray-900',
  '唤灵师': 'bg-gray-300 text-gray-900',
  'Revenant': 'bg-indigo-100 text-indigo-800',
  '魂武者': 'bg-indigo-100 text-indigo-800',
  'Berserker': 'bg-red-100 text-red-800',
  '狂战士': 'bg-red-100 text-red-800',
  'Spellbreaker': 'bg-red-100 text-red-800',
  '破法者': 'bg-red-100 text-red-800',
  'Willbender': 'bg-red-100 text-red-800',
  '誓剑士': 'bg-red-100 text-red-800',
  'Dragonhunter': 'bg-yellow-100 text-yellow-800',
  '圣言士': 'bg-yellow-100 text-yellow-800',
  'Tempest': 'bg-cyan-100 text-cyan-800',
  '燃火者': 'bg-cyan-100 text-cyan-800',
  'Weaver': 'bg-cyan-100 text-cyan-800',
  '破锋者': 'bg-cyan-100 text-cyan-800',
  'Catalyst': 'bg-cyan-100 text-cyan-800',
  '龙卫': 'bg-cyan-100 text-cyan-800',
  'Chronomancer': 'bg-purple-100 text-purple-800',
  '圣辉者': 'bg-purple-100 text-purple-800',
  'Herald': 'bg-indigo-100 text-indigo-800',
  '预告者': 'bg-indigo-100 text-indigo-800',
  'Renegade': 'bg-indigo-100 text-indigo-800',
  '龙魂使': 'bg-indigo-100 text-indigo-800',
  'Vindicator': 'bg-indigo-100 text-indigo-800',
  '裁决者': 'bg-indigo-100 text-indigo-800',
  'Druid': 'bg-green-100 text-green-800',
  '德鲁伊': 'bg-green-100 text-green-800',
  'Soulbeast': 'bg-green-100 text-green-800',
  '魂兽师': 'bg-green-100 text-green-800',
  'Untamed': 'bg-green-100 text-green-800',
  '狂兽师': 'bg-green-100 text-green-800',
  'Deadeye': 'bg-gray-200 text-gray-800',
  '风羽者': 'bg-gray-200 text-gray-800',
  'Scrapper': 'bg-orange-100 text-orange-800',
  '机械师': 'bg-orange-100 text-orange-800',
  'Holosmith': 'bg-orange-100 text-orange-800',
  '全息师': 'bg-orange-100 text-orange-800',
  'Mechanist': 'bg-orange-100 text-orange-800',
  '玉偃师': 'bg-orange-100 text-orange-800',
  'Daredevil': 'bg-gray-200 text-gray-800',
  '流金师': 'bg-gray-200 text-gray-800',
  'Specter': 'bg-gray-200 text-gray-800',
  '独行侠': 'bg-gray-200 text-gray-800',
  'Deadeye': 'bg-gray-200 text-gray-800',
  '神枪手': 'bg-gray-200 text-gray-800',
  'Mirage': 'bg-purple-100 text-purple-800',
  '缚影者': 'bg-purple-100 text-purple-800',
  'Virtuoso': 'bg-purple-100 text-purple-800',
  '夜刃': 'bg-purple-100 text-purple-800',
  'Reaper': 'bg-gray-300 text-gray-900',
  '夺魂者': 'bg-gray-300 text-gray-900',
  'Scourge': 'bg-gray-300 text-gray-900',
  '灾厄师': 'bg-gray-300 text-gray-900',
  'Harbinger': 'bg-gray-300 text-gray-900',
  '先驱者': 'bg-gray-300 text-gray-900',
  'Weaver': 'bg-gray-300 text-gray-900',
  '祭祀者': 'bg-gray-300 text-gray-900',
  'Chronomancer': 'bg-purple-100 text-purple-800',
  '时空术士': 'bg-purple-100 text-purple-800',
  'Mirage': 'bg-purple-100 text-purple-800',
  '幻象术士': 'bg-purple-100 text-purple-800',
  'Virtuoso': 'bg-purple-100 text-purple-800',
  '灵刃术士': 'bg-purple-100 text-purple-800',
  'Mesmer': 'bg-purple-100 text-purple-800',
  '吟游诗人': 'bg-purple-100 text-purple-800'
}

export const translateProfession = (profession) => {
  if (!profession) return '未知'
  return PROFESSION_TRANSLATIONS[profession] || profession
}

export const getProfessionClass = (profession) => {
  return PROFESSION_COLORS[profession] || 'bg-gray-100 text-gray-600'
}